name: Test, Build

on:
  push:
    branches: [ "main", "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm i

    - name: Test
      run: npm test